apiVersion: 1
datasources:
- name: Prometheus
  type: prometheus
  # url: http://host.docker.internal:9090 In case you are running on Mac or Linux
  url: http://172.17.0.1:9090
  isDefault: true
  access: proxy
  editable: true
